version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: filament
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple-fm
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U filament -d simple-fm']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '8080:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_URL: postgres://filament:secret@db:5432/simple-fm
      NODE_ENV: development
      PORT: 3000
    env_file:
      - .env

volumes:
  pgdata:
